import { describe, it, expect, beforeAll } from 'vitest';
import { cube3x3x3 } from 'cubing/puzzles';
import { Alg } from 'cubing/alg';
import { CaseMatcher } from '../solver/caseMatcher';
import { simplifyMoveSequence, simplifyAlgString } from '../utils/moveSimplifier';
import { isSlotSolved, isCrossSolved, type F2LSlot } from '../solver/cfopInvariants';
import algorithmData from '../data/cfop-algorithms.json';

describe('Move Simplifier & Cancellation', () => {
  it('correctly merges consecutive turns on the same face', () => {
    expect(simplifyMoveSequence(['U2', "U'"])).toEqual(['U']);
    expect(simplifyMoveSequence(["U'", "U'"])).toEqual(['U2']);
    expect(simplifyMoveSequence(['U', 'U'])).toEqual(['U2']);
    expect(simplifyMoveSequence(['U', "U'"])).toEqual([]);
    expect(simplifyMoveSequence(['R2', 'R2'])).toEqual([]);
    expect(simplifyMoveSequence(['R', 'R2'])).toEqual(["R'"]);
    expect(simplifyMoveSequence(['F', "F'", 'U'])).toEqual(['U']);
  });

  it('correctly commutes and cancels across parallel faces', () => {
    expect(simplifyMoveSequence(['U', 'D', "U'"])).toEqual(['D']);
    expect(simplifyMoveSequence(['R', 'L', "R'"])).toEqual(['L']);
    expect(simplifyMoveSequence(['F2', 'B', 'F2'])).toEqual(['B']);
  });

  it('simplifies full algorithm strings', () => {
    expect(simplifyAlgString("U2 U' R U R' U'")).toBe("U R U R' U'");
    expect(simplifyAlgString("U' U' R U' R'")).toBe("U2 R U' R'");
  });

});

describe('CFOP Case Matcher', () => {
  let matcher: CaseMatcher;
  let kp: any;
  let solvedPostZ2: any;

  beforeAll(async () => {
    kp = await cube3x3x3.kpuzzle();
    solvedPostZ2 = kp.defaultPattern().applyAlg(new Alg('z2'));
    matcher = new CaseMatcher(kp);
    matcher.initialize(algorithmData as any);
  });

  it('correctly matches OLL cases generated by inverted algorithms', () => {
    // Pick Sune: (R U R' U) (R U2' R')
    const suneAlg = "(R U R' U) (R U2' R')";
    const invSune = new Alg(suneAlg).invert();
    const testPattern = solvedPostZ2.applyAlg(invSune);

    const match = matcher.matchOLL(testPattern);
    expect(match).not.toBeNull();
    expect(match?.caseName).toContain('Sune');
  });

  it('correctly matches PLL cases generated by inverted algorithms', () => {
    // Pick T-Perm: (R U R' U') (R' F R2) (U' R' U') (R U R' F')
    const tPermAlg = "(R U R' U') (R' F R2) (U' R' U') (R U R' F')";
    const invTPerm = new Alg(tPermAlg).invert();
    const testPattern = solvedPostZ2.applyAlg(invTPerm);

    const match = matcher.matchPLL(testPattern);
    expect(match).not.toBeNull();
    expect(match?.caseName).toContain('T Perm');
  });

  it('matches OLL under pre-AUF rotation without redundant moves', () => {
    const suneAlg = "(R U R' U) (R U2' R')";
    const invSuneWithU = new Alg(`U ${new Alg(suneAlg).invert().toString()}`);
    const testPattern = solvedPostZ2.applyAlg(invSuneWithU);

    const match = matcher.matchOLL(testPattern);
    expect(match).not.toBeNull();
    expect(match?.caseName).toContain('Sune');
    // Ensure no redundant adjacent U moves
    for (let i = 0; i < (match?.moves.length || 0) - 1; i++) {
      const m1 = match!.moves[i];
      const m2 = match!.moves[i + 1];
      expect(m1[0] === m2[0] && (m1[0] === 'U' || m1[0] === 'D')).toBe(false);
    }
  });

  it('correctly matches 2-Look OLL (Yellow Cross & Corners) from 10 allowed algorithms', () => {
    // 1. Edge Cross - Line
    const lineAlg = "F R U R' U' F'";
    const invLine = new Alg(lineAlg).invert();
    const testPatternLine = solvedPostZ2.applyAlg(invLine);
    const matchLine = matcher.match2LookOLL(testPatternLine);
    expect(matchLine).not.toBeNull();
    expect(matchLine?.caseName).toContain('2-Look OLL');

    // 2. Corner - Sune
    const suneAlg = "R U R' U R U2 R'";
    const invSune = new Alg(suneAlg).invert();
    const testPatternSune = solvedPostZ2.applyAlg(invSune);
    const matchSune = matcher.match2LookOLL(testPatternSune);
    expect(matchSune).not.toBeNull();
    expect(matchSune?.caseName).toContain('Sune');
  });

  it('correctly returns single-layer turns in simplified notation mode and standard moves in standard mode', () => {
    // Inverted Aa-Perm
    const aaAlg = "x (R' U R') D2 (R U' R') D2 R2 x'";
    const testPatternAa = solvedPostZ2.applyAlg(new Alg(aaAlg).invert());

    const simplifiedAa = matcher.match2LookPLL(testPatternAa, 'simplified');
    expect(simplifiedAa).not.toBeNull();
    // In simplified mode, Aa-Perm must have ZERO rotations or slice moves
    expect(simplifiedAa?.moves.some((m) => /[frludbMSExyz]/.test(m))).toBe(false);
    expect(simplifiedAa?.algorithm).toBe("R' F R' B2 R F' R' B2 R2");

    const standardAa = matcher.match2LookPLL(testPatternAa, 'standard');
    expect(standardAa).not.toBeNull();
    expect(standardAa?.moves.some((m) => m.startsWith('x'))).toBe(true);

    // Inverted H-Perm
    const hAlg = "M2 (U') M2 (U2') M2 (U') M2";
    const testPatternH = solvedPostZ2.applyAlg(new Alg(hAlg).invert());

    const simplifiedH = matcher.match2LookPLL(testPatternH, 'simplified');
    expect(simplifiedH).not.toBeNull();
    expect(simplifiedH?.moves.some((m) => /[frludbMSExyz]/.test(m))).toBe(false);

    const standardH = matcher.match2LookPLL(testPatternH, 'standard');
    expect(standardH).not.toBeNull();
    expect(standardH?.moves.some((m) => m.startsWith('M'))).toBe(true);
  });


  it('correctly matches Intuitive F2L without any wide f moves across all slots', () => {

    const slots = [
      { slot: 'FR', inv: "R U R' U'" },
      { slot: 'FL', inv: "L' U' L U" },
      { slot: 'BR', inv: "R' U' R U" },
      { slot: 'BL', inv: "L U L' U'" },
    ];

    for (const { slot, inv } of slots) {
      const testPattern = solvedPostZ2.applyAlg(new Alg(inv));
      const match = matcher.matchIntuitiveF2L(testPattern, slot);

      expect(match).not.toBeNull();
      expect(match?.targetSlot).toBe(slot);

      // Verify ZERO wide or slice moves exist in intuitive guidance
      const hasWideOrSliceMoves = match?.moves.some((m) => /[frludbMSE]/.test(m));
      expect(hasWideOrSliceMoves).toBe(false);

      // Verify no duplicate adjacent same-face moves
      for (let i = 0; i < (match?.moves.length || 0) - 1; i++) {
        const m1 = match!.moves[i];
        const m2 = match!.moves[i + 1];
        expect(m1[0] === m2[0]).toBe(false);
      }
    }
  });

  it('correctly solves trapped F2L pieces with multi-step extraction and insertion', () => {
    // Corner is trapped in FR slot with twisted orientation, edge in U layer
    // Generated by: R U R' U' (standard insertion) followed by R U R' (trapping corner in slot)
    const trapAlg = new Alg("R U R' U R U R'");
    const testPattern = solvedPostZ2.applyAlg(trapAlg);

    const match = matcher.matchIntuitiveF2L(testPattern, 'FR');
    expect(match).not.toBeNull();
    expect(match?.targetSlot).toBe('FR');
    expect(match?.moves.length).toBeGreaterThan(0);

    // Apply the solution to verify it genuinely solves the FR slot
    const solvedPattern = testPattern.applyAlg(new Alg(match!.moves.join(' ')));
    const edges = solvedPattern.patternData.EDGES;
    const corners = solvedPattern.patternData.CORNERS;

    // FR corner (slot 4, piece 3) and FR edge (slot 8, piece 9)
    expect(corners.pieces[4]).toBe(3);
    expect(corners.orientation[4]).toBe(0);
    expect(edges.pieces[8]).toBe(9);
    expect(edges.orientation[8]).toBe(0);
  });

  it('correctly extracts a piece trapped in a different slot (e.g. FL piece trapped in BR)', () => {
    // Generate a state where FL edge is trapped in BR slot:
    // Move FL edge (slot 9) into BR slot (slot 10) using R' U' R U L' U L
    const trapAlg = new Alg("L' U' L U R' U R");
    const testPattern = solvedPostZ2.applyAlg(trapAlg);

    const match = matcher.matchIntuitiveF2L(testPattern, 'FL');
    expect(match).not.toBeNull();
    expect(match?.targetSlot).toBe('FL');
    expect(match?.moves.length).toBeGreaterThan(0);

    // Verify it used an extraction that touches the trap slot (BR turns R' / B)
    const hasExtractMoves = match?.moves.some((m) => m.startsWith('R') || m.startsWith('B') || m.startsWith('L'));
    expect(hasExtractMoves).toBe(true);

    // Apply the solution to verify it genuinely solves the FL slot
    const solvedPattern = testPattern.applyAlg(new Alg(match!.moves.join(' ')));
    const edges = solvedPattern.patternData.EDGES;
    const corners = solvedPattern.patternData.CORNERS;

    // FL corner (slot 5, piece 0) and FL edge (slot 9, piece 8)
    expect(corners.pieces[5]).toBe(0);
    expect(corners.orientation[5]).toBe(0);
    expect(edges.pieces[9]).toBe(8);
    expect(edges.orientation[9]).toBe(0);
  });

  it('matchF2L never returns a no-op for an already-solved slot (regression: "goes in circles")', () => {
    // FR is solved; FL pair sits in the U layer ready to insert. Ask for FL.
    const pattern = solvedPostZ2.applyAlg(new Alg("F' L F L'").invert()); // FL case setup, FR still solved
    expect(isSlotSolved(pattern, 'FR')).toBe(true);
    expect(isSlotSolved(pattern, 'FL')).toBe(false);

    const match = matcher.matchF2L(pattern, 'FL', false, 'simplified');
    expect(match).not.toBeNull();
    expect(match!.moves.length).toBeGreaterThan(0);

    const after = pattern.applyAlg(new Alg(match!.moves.join(' ')));
    expect(isSlotSolved(after, 'FL'), 'FL must actually be solved').toBe(true);
    expect(isSlotSolved(after, 'FR'), 'FR must stay solved').toBe(true);
    expect(isCrossSolved(after)).toBe(true);
    // and it must not be the FR "U R U' R'" no-op
    expect(match!.moves.join(' ')).not.toBe("U R U' R'");
  });

  it('every F2L slot variant solves its own slot from the dataset', () => {
    const cases: Array<[F2LSlot, string]> = [
      ['FR', 'F2L 1 - Front Right'],
      ['FL', 'F2L 1 - Front Left'],
      ['BR', 'F2L 1 - Back Right'],
      ['BL', 'F2L 1 - Back Left'],
      ['FR', 'F2L 18 - Front Right'],
      ['FL', 'F2L 18 - Front Left'],
      ['BR', 'F2L 18 - Back Right'],
      ['BL', 'F2L 18 - Back Left'],
    ];
    for (const [slot, name] of cases) {
      const entry = (algorithmData as any).F2L.find((e: any) => e.name === name);
      const setup = solvedPostZ2.applyAlg(new Alg(entry.algorithm).invert());
      const match = matcher.matchF2L(setup, slot, false, 'standard');
      expect(match, name).not.toBeNull();
      const after = setup.applyAlg(new Alg(match!.moves.join(' ')));
      expect(isSlotSolved(after, slot), `${name} -> ${slot}`).toBe(true);
    }
  });
});




